using System;

namespace PUBGMobileConfigDecrypter
{
    internal sealed class Encryption
    {
        public static string Decrypt(string encryptedCharacter)
        {
            switch (encryptedCharacter)
            {
                case "48":
                    return "1";
                case "4B":
                    return "2";
                case "4A":
                    return "3";
                case "4D":
                    return "4";
                case "4C":
                    return "5";
                case "4F":
                    return "6";
                case "4E":
                    return "7";
                case "41":
                    return "8";
                case "40":
                    return "9";
                case "49":
                    return "0";
                case "38":
                    return "A";
                case "3B":
                    return "B";
                case "3A":
                    return "C";
                case "3D":
                    return "D";
                case "3C":
                    return "E";
                case "3F":
                    return "F";
                case "3E":
                    return "G";
                case "31":
                    return "H";
                case "30":
                    return "I";
                case "33":
                    return "J";
                case "32":
                    return "K";
                case "35":
                    return "L";
                case "34":
                    return "M";
                case "37":
                    return "N";
                case "36":
                    return "O";
                case "29":
                    return "P";
                case "28":
                    return "Q";
                case "2B":
                    return "R";
                case "2A":
                    return "S";
                case "2D":
                    return "T";
                case "2C":
                    return "U";
                case "2F":
                    return "V";
                case "2E":
                    return "W";
                case "21":
                    return "X";
                case "20":
                    return "Y";
                case "23":
                    return "Z";
                case "18":
                    return "a";
                case "1B":
                    return "b";
                case "1A":
                    return "c";
                case "1D":
                    return "d";
                case "1C":
                    return "e";
                case "1F":
                    return "f";
                case "1E":
                    return "g";
                case "11":
                    return "h";
                case "10":
                    return "i";
                case "13":
                    return "j";
                case "12":
                    return "k";
                case "15":
                    return "l";
                case "14":
                    return "m";
                case "17":
                    return "n";
                case "16":
                    return "o";
                case "09":
                    return "p";
                case "08":
                    return "q";
                case "0B":
                    return "r";
                case "0A":
                    return "s";
                case "0D":
                    return "t";
                case "0C":
                    return "u";
                case "0F":
                    return "v";
                case "0E":
                    return "w";
                case "01":
                    return "x";
                case "00":
                    return "y";
                case "03":
                    return "z";
                case "44":
                    return "=";
                case "57":
                    return ".";
            }

            throw new ArgumentException($@"Unexpected character {encryptedCharacter}!", nameof(encryptedCharacter));
        }

        public static string Encrypt(char plaintextCharacter)
        {
            switch (plaintextCharacter)
            {
                case '1':
                    return "48";
                case '2':
                    return "4B";
                case '3':
                    return "4A";
                case '4':
                    return "4D";
                case '5':
                    return "4C";
                case '6':
                    return "4F";
                case '7':
                    return "4E";
                case '8':
                    return "41";
                case '9':
                    return "40";
                case '0':
                    return "49";
                case 'A':
                    return "38";
                case 'B':
                    return "3B";
                case 'C':
                    return "3A";
                case 'D':
                    return "3D";
                case 'E':
                    return "3C";
                case 'F':
                    return "3F";
                case 'G':
                    return "3E";
                case 'H':
                    return "31";
                case 'I':
                    return "30";
                case 'J':
                    return "33";
                case 'K':
                    return "32";
                case 'L':
                    return "35";
                case 'M':
                    return "34";
                case 'N':
                    return "37";
                case 'O':
                    return "36";
                case 'P':
                    return "29";
                case 'Q':
                    return "28";
                case 'R':
                    return "2B";
                case 'S':
                    return "2A";
                case 'T':
                    return "2D";
                case 'U':
                    return "2C";
                case 'V':
                    return "2F";
                case 'W':
                    return "2E";
                case 'X':
                    return "21";
                case 'Y':
                    return "20";
                case 'Z':
                    return "23";
                case 'a':
                    return "18";
                case 'b':
                    return "1B";
                case 'c':
                    return "1A";
                case 'd':
                    return "1D";
                case 'e':
                    return "1C";
                case 'f':
                    return "1F";
                case 'g':
                    return "1E";
                case 'h':
                    return "11";
                case 'i':
                    return "10";
                case 'j':
                    return "13";
                case 'k':
                    return "12";
                case 'l':
                    return "15";
                case 'm':
                    return "14";
                case 'n':
                    return "17";
                case 'o':
                    return "16";
                case 'p':
                    return "09";
                case 'q':
                    return "08";
                case 'r':
                    return "0B";
                case 's':
                    return "0A";
                case 't':
                    return "0D";
                case 'u':
                    return "0C";
                case 'v':
                    return "0F";
                case 'w':
                    return "0E";
                case 'x':
                    return "01";
                case 'y':
                    return "00";
                case 'z':
                    return "03";
                case '=':
                    return "44";
                case '.':
                    return "57";
            }

            throw new ArgumentException($@"Unexpected character {plaintextCharacter}", nameof(plaintextCharacter));
        }
    }
}
